### ISSUE TITLE
在Lua中使用player:speak(".StartBgMusic")失效

### ISSUE THREAD

**Issue by wch5621628** [Mogara/QSanguosha-v2#10]
在聊天框键入.StartBgMusic却可以。

**Comment by Fsu0413** [comment]
.StartBgMusic是从客户端输入的指令，不传到服务器的，在服务器直接输入.StartBgMusic的话，在客户端是没有响应的，这不是Bug，代码的设计就是这样的。

**Comment by wch5621628** [comment]
好的谢谢，能用json来speak么?

**Comment by wch5621628** [comment]
好的谢谢
