### ISSUE TITLE
centos7下带 -server参数运行会coredump

### ISSUE THREAD

**Issue by WilliamShi** [Mogara/QSanguosha-v2#107]
从这里git clone的源码编译后运行一切正常，就是带-server参数运行会coredump

**Comment by Fsu0413** [comment]
好像-server出了问题。。。。我这边Windows也起不来了

**Comment by WilliamShi** [comment]
这个现在还有人解决不，因为好像看到说V2版本已经不再维护，不过这个-server功能对于玩单机版的似乎没什么大用处，但对于要起服务器的人来说很有用，对于推广也能起更大的作用

**Comment by Fsu0413** [comment]
但是。。。其实之前我建立的服务器都是有界面的我会乱说么。。。。。。
0926有官方服务器的，就是我弄的，服务器里是Windows系统

**Comment by WilliamShi** [comment]
我当然知道你不会乱说了，我只是说我之前建立过服务器是可以带-server参数运行没有界面的

**Comment by Fsu0413** [comment]
所以这是个迷啊。。。。。好久没调试过带server参数的了，不过这个分支就这样吧。。。

**Comment by WilliamShi** [comment]
那现在哪个分支是最新的呢？

**Comment by Fsu0413** [comment]
就是这个已经停更的是最新
