### ISSUE TITLE
在 config.lua 中注掉"Nostalgia", AI只会摸牌弃牌

### ISSUE THREAD

**Issue by aa3615058** [Mogara/QSanguosha-v2#108]
我在源码中去掉了这个卡牌包的唯一卡牌 MoonSpear，对AI没有影响。
但是如果这个空包不在config.lua中的话，AI只会摸牌弃牌。
查了半天源码和lua的ai脚本，不知道问题出在哪。

**Comment by Fsu0413** [comment]
会导致不读取nostalgia-ai.lua
