### ISSUE TITLE
win7下编译运行没有声音

### ISSUE THREAD

**Issue by icexin** [Mogara/QSanguosha-v2#120]
我下载的是master的代码，使用qt5.5编译的，编译完之后我把二进制拷贝到QSanguosha-v2-20170211目录下运行，没有一点声音。运行QSanguosha-v2-20170211原来的二进制是有声音的。QSanguosha-v2-20170211是从贴吧里面的地址下载的zip包。

**Comment by omnisreen** [comment]
#118 
#116

**Comment by Fsu0413** [comment]
dup
