### ISSUE TITLE
用最新的QT5.9.1编译，运行游戏存在阴影

### ISSUE THREAD

**Issue by ghost** [Mogara/QSanguosha-v2#122]
我用QT5.9.1编译V2项目，去掉了 QtDeclarative 模块，运行游戏后动画上存在重影，有很明显的影子轨迹，武将的名字一闪一闪，不知道是不是新版本的GraphicsView有问题。

**Comment by LiXiaYu** [comment]
我也想用新版编译
发一份给我啊，自己做总是去不干净
谢谢了

**Comment by alex10529** [comment]
我也是,我用的是QT5.9.0,MSVC2017 ,X64,游戏动画有重影,而且极不稳定,经常闪退,

**Comment by LiXiaYu** [comment]
话说你们都是怎么编译的？新版本好多组件丢了，我都改不好。。。

**Comment by ghost** [comment]
@alex10529 @LiXiaYu      最新版  Qt 5.9.2 已解决此问题。

**Comment by alex10529** [comment]
@LiXiaYu QT5.6之前的declarative要换成 qml quick,
相应的QDeclarativeXXX也要换成QQmlXXX，可以全文搜索工程，祝你好运。

**Comment by Fsu0413** [comment]
5.5.1没问题。
我确实有打算通过重构来解决神杀的历史问题，不过现在时间太少

**Comment by Fsu0413** [comment]
5.5.1没问题。
我确实有打算通过重构来解决神杀的历史问题，不过现在时间太少

**Comment by Fsu0413** [comment]
先关闭。
5.5都没有问题。接到反馈5.9也没问题，认为是Qt的bug。
