### ISSUE TITLE
用qt5.9.2编译后，debug模式会停止运行，release模式可以运行

### ISSUE THREAD

**Issue by LiXiaYu** [Mogara/QSanguosha-v2#125]
qt5.9.2msvc15 x64 windows10

**Comment by yuexian1234** [comment]
用5.9.2编译没问题吗?比如提示QtDeclarative no such file 你怎么解决的

**Comment by yuexian1234** [comment]
还有qt5和qt4 好多函数也不一样了吧 你怎么搞的

**Comment by LiXiaYu** [comment]
@cheyuexian QtDeclarative在qt5中被对应替换了，可以百度到相关的官方文档和资料。真的，只是替换了类名，接口都一样的，很简单。神杀里面应该只有这几个，而且你可以看看我fork的版本，我自己配的，并不允许发布，也不允许直接复制，因为开源协议有问题，所以，你只可以看看，**千万**不**要随便复制走**

**Comment by LiXiaYu** [comment]
以及，不要偏题啊
话说，现在都是怎么debug的？@Fsu0413

**Comment by WilliamShi** [comment]
用Qt5.9.2 在unbuntu 16.06 LTS 64bit上今天编译了一下，只有因为Qt4到Qt5要改的几个类，编译出来在服务器模式下运行成功

**Comment by Fsu0413** [comment]
Debug早就死了，程序里有历史问题导致跨线程setProperty会assert

**Comment by LiXiaYu** [comment]
这就特别尴尬啊，也就是说，神杀已经进入不可维护状态了。。。

**Comment by LiXiaYu** [comment]
所以咱们来写个新的吧。。。

**Comment by Fsu0413** [comment]
所以我现在正在重构东方杀，虽然进度很缓慢
一点一点解决历史问题吧。。。。。

**Comment by LiXiaYu** [comment]
@Fsu0413 dalao好强，我也想女装

**Comment by Fsu0413** [comment]
@LiXiaYu 要不要参与开发

**Comment by LiXiaYu** [comment]
@Fsu0413 可以的啊

**Comment by Fsu0413** [comment]
@LiXiaYu 加过东方杀的群么，没加的话加下 384318315

**Comment by LiXiaYu** [comment]
@Fsu0413 加群了啊，dalao，虽然我还是找不到代码在哪里。。。

**Comment by LiXiaYu** [comment]
放弃维护了吗？关闭issue
