### ISSUE TITLE
求开启AI身份预知

### ISSUE THREAD

**Issue by HiddenTesla** [Mogara/QSanguosha-v2#127]
目前AI的身份判断能力不太好，经常会出现攻击自己人的情况。尤其是自定义的技能。

2011年左右的神杀的AI是直接知道所有人身份的。这样虽然有点无赖，但总比自相残杀要好吧。。。

**Comment by Sanluli36li** [comment]
讲道理当年的ai甚至是不受锁定技控制的
比如有阵子ai不会判断完杀强行给人喂桃子
话说回来这种东西可以考虑加一个选项

**Comment by Fsu0413** [comment]
@36li 讲道理不受锁定技控制的AI完杀是因为完杀改了，AI没同步更新而已
完杀最早的实现方法是AskForPeaches时机返回true中止结算，后来出了三将成名曹冲仁心改了结算，这个时机不能中止结算了，才导致的
本来完杀应该是setPlayerCardLimitation禁桃的，但是由于种种原因没这么做

**Comment by LiXiaYu** [comment]
@Fsu0413 所以说什么时候开新坑。。。感觉这破程序乙烷了、、、

**Comment by Fsu0413** [comment]
@LiXiaYu 本来就乙烷了。。。我在15年9月就宣布停止更新了

**Comment by sunnyadn** [comment]
QSanguosha will be ported to [CYOU](https://cyouapp.com), a cutting-edge framework originated from Mogara, with much fantastic and modern features.
