### ISSUE TITLE
求问一下Qt版本

### ISSUE THREAD

**Issue by Michaelbest1** [Mogara/QSanguosha-v2#129]
我试了3个qt版本，分别是4.8, 5.6和5.10。4.8提示头文件QtDeclarative和QtWidgets找不到，5.6和5.10提示QtDeclarative找不到。
vs2013.readme里面有一个配置change the configuration to Release Qt5|Win32，这个要怎么配置呢？我没找到哪里可以修改这个配置。
我用的就是VS2013，操作系统是win10。求助一下。谢谢！

**Comment by LiXiaYu** [comment]
这个确实是找不到了，被替换成了qml quick，详细情况要看http://doc.qt.io/qt-5/qtquick-porting-qt5.html

Qt QML | Qt Quick
-- | --
QDeclarativeComponent -> QQmlComponentQDeclarativeContext -> QQmlContextQDeclarativeEngine -> QQmlEngineQDeclarativeError -> QQmlErrorQDeclarativeExpression -> QQmlExpressionQDeclarativeExtensionPlugin -> QQmlExtensionPluginQDeclarativeInfo -> QQmlInfoQDeclarativeListReference -> QQmlListReferenceQDeclarativeNetworkAccessManagerFactory -> QQmlNetworkAccessManagerFactoryQDeclarativeParserStatus -> QQmlParserStatusQDeclarativeProperty -> QQmlPropertyQDeclarativePropertyMap -> QQmlPropertyMapQDeclarativePropertyValueSource -> QQmlPropertyValueSourceQDeclarativeScriptString -> QQmlScriptString | QDeclarativeItem -> QQuickItemQDeclarativeView -> QQuickViewQDeclarativeImageProvider -> QQuickImageProvider

**Comment by Fsu0413** [comment]
5.5.1

**Comment by Michaelbest1** [comment]
我准备去编译国战版了，这个先不管了: P
不过还是要谢谢回复哈

**Comment by Michaelbest1** [comment]
不过还是要谢谢回复哈
