### ISSUE TITLE
编译之前是不是要安装FMOD？

### ISSUE THREAD

**Issue by bioxun** [Mogara/QSanguosha-v2#131]
我看到有这样的代码 static FMOD_SYSTEM *System; 不被识别。

如果是的话，那是要装哪个FMOD呢，安装到哪里有什么要求吗？

**Comment by bioxun** [comment]
我看到gibhub的comment里面说了kill fmod，但是QSanguosha-v2-master\src\core\audio.cpp等文件里面还是用到fmod，这怎么解决的？

**Comment by DGAH** [comment]
@bioxun 好像并没有解决的样子……应该的确是会报这个错误。
用那个comment之前一次的版本编译试试？

**Comment by bioxun** [comment]
@DGAH comment之前一次的版本怎么下载？

**Comment by LiXiaYu** [comment]
@bioxun 可以去我的fork版本里面去拉fmod部分出来

**Comment by DGAH** [comment]
@bioxun 找到对应的comment后，点进去，再点页面右上部分的“Browse files”按钮，就能看到那个时间点上的项目全貌了。
这是链接：
https://github.com/Mogara/QSanguosha-v2/tree/11a49f9672166d1de2ba13cba31b8c4d89102756

**Comment by bioxun** [comment]
@DGAH 多谢！

**Comment by Fsu0413** [comment]
Fmod因为license的原因被干掉了，你们如果想用的话可以自己弄
之前有个Issue的内容可以参考
