### ISSUE TITLE
如果要使每次洛神都发音，应该对哪些文件中的代码进行修改？

### ISSUE THREAD

**Issue by bioxun** [Mogara/QSanguosha-v2#133]
目前在甄姬每个回合中，只有第一下洛神会发出声音，之后就不会发出声音了。例如，连续5黑，也只会发声一次。
那么为了跟online一样，让每次洛神摸牌都发声，应该对哪些文件进行修改？

**Comment by bioxun** [comment]
有没有文档整体上介绍哪些功能是由哪些文件实现的？例如，配音是由哪些程序实现的，牌局进程外观是由哪些程序实现的。

**Comment by Fsu0413** [comment]
你问到了硬伤，没错，现在就是没有

**Comment by Fsu0413** [comment]
改SRC/package/啥来着忘了，反正就是找到里面有个技能叫luoshen，把broadcastskillinvoke相关逻辑进行修改
