### ISSUE TITLE
怎么切换界面语言？

### ISSUE THREAD

**Issue by bioxun** [Mogara/QSanguosha-v2#134]
我遇到一个诡异的情况：
昨天我用vc编译成功，得到的是英文版的界面，但是不知怎么的今天就变成了中文版的界面了。
虽然今天我用Qt creater也编译了一个，但是并没有覆盖原来的文件，应该没有影响才是。
怎么解释这个现象？

更重要的是，如果现在想切换回英文版的界面应该怎么办？

**Comment by Fsu0413** [comment]
没有选项，现在只有中文
