### ISSUE TITLE
sanguosha.qm这个文件是怎么生成的？

### ISSUE THREAD

**Issue by bioxun** [Mogara/QSanguosha-v2#135]
我在源文件文件夹中没有找到sanguosha.qm存在；
我在build了QSanguosha.pro之后也没发现sanguosha.qm生成；
然而奇怪的是不知道什么时候sanguosha.qm就突然出现了。

这是怎么回事？

**Comment by Fsu0413** [comment]
lrelease QSanguosha.pro
