### ISSUE TITLE
请问有4k屏的解决方案吗

### ISSUE THREAD

**Issue by KiritoStudio** [Mogara/QSanguosha-v2#140]
Windows下字太小了，眼睛要瞎了（哭）

**Comment by Fsu0413** [comment]
无

**Comment by KiritoStudio** [comment]
附一个Windows(Windows 10 Enterprise 20H2)下的解决方案：
application property -> Compatibility -> Change high DPI settings -> Check "Use this setting to fix scaling problems for this program instead of the one in Settings" -> Choose "I open this program" -> Check "Override high DPI scaling behavior." -> Choose "System(Enhanced)"
