### ISSUE TITLE
Mac下的编译错误

### ISSUE THREAD

**Issue by KiritoStudio** [Mogara/QSanguosha-v2#141]
环境：
MacOS 10.13.6
Qt 5.4
swig 3.0.5

日志如下：
20:37:53: Running steps for project QSanguosha...
20:37:53: Configuration unchanged, skipping qmake step.
20:37:53: Starting: "/usr/bin/make" 
/Users/kirito/Qt5.4.2/5.4/clang_64/bin/uic ../QSanguosha-v2/src/dialog/cardoverview.ui -o ui_cardoverview.h
/Users/kirito/Qt5.4.2/5.4/clang_64/bin/uic ../QSanguosha-v2/src/dialog/configdialog.ui -o ui_configdialog.h
/Users/kirito/Qt5.4.2/5.4/clang_64/bin/uic ../QSanguosha-v2/src/dialog/connectiondialog.ui -o ui_connectiondialog.h
/Users/kirito/Qt5.4.2/5.4/clang_64/bin/uic ../QSanguosha-v2/src/dialog/generaloverview.ui -o ui_generaloverview.h
/Users/kirito/Qt5.4.2/5.4/clang_64/bin/uic ../QSanguosha-v2/src/dialog/mainwindow.ui -o ui_mainwindow.h
/Users/kirito/Qt5.4.2/5.4/clang_64/bin/uic ../QSanguosha-v2/src/dialog/mainwindowserverlist.ui -o ui_mainwindowserverlist.h
/Users/kirito/Qt5.4.2/5.4/clang_64/bin/uic ../QSanguosha-v2/src/dialog/dialogslsettings.ui -o ui_dialogslsettings.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC -DUSING_PCH -DMAC -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -I../QSanguosha-v2 -I. -I../QSanguosha-v2/include -I../QSanguosha-v2/src/client -I../QSanguosha-v2/src/core -I../QSanguosha-v2/src/dialog -I../QSanguosha-v2/src/package -I../QSanguosha-v2/src/scenario -I../QSanguosha-v2/src/server -I../QSanguosha-v2/src/ui -I../QSanguosha-v2/src/util -I../QSanguosha-v2/src/lua -I../QSanguosha-v2/include/freetype -I../../../Qt5.4.2/5.4/clang_64/lib/QtDeclarative.framework/Versions/5/Headers -I../../../Qt5.4.2/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Qt5.4.2/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Qt5.4.2/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../../Qt5.4.2/5.4/clang_64/lib/QtScript.framework/Versions/5/Headers -I../../../Qt5.4.2/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt5.4.2/5.4/clang_64/mkspecs/macx-clang -F/Users/kirito/Qt5.4.2/5.4/clang_64/lib -x c++-header -c ../QSanguosha-v2/src/pch.h -o QSanguosha/c++.pch
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../QSanguosha-v2/src/pch.h:14:
In file included from ../../../Qt5.4.2/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtCore:4:
In file included from ../../../Qt5.4.2/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstractanimation.h:37:
In file included from /Users/kirito/Qt5.4.2/5.4/clang_64/lib/QtCore.framework/Headers/qobject.h:40:
In file included from /Users/kirito/Qt5.4.2/5.4/clang_64/lib/QtCore.framework/Headers/qobjectdefs.h:41:
In file included from /Users/kirito/Qt5.4.2/5.4/clang_64/lib/QtCore.framework/Headers/qnamespace.h:37:
In file included from /Users/kirito/Qt5.4.2/5.4/clang_64/lib/QtCore.framework/Headers/qglobal.h:70:
/Users/kirito/Qt5.4.2/5.4/clang_64/lib/QtCore.framework/Headers/qcompilerdetection.h:890:11: fatal error: 'utility' file not found
`# include <utility>`
          ^~~~~~~~~
1 warning and 1 error generated.
make: *** [QSanguosha/c++.pch] Error 1
20:37:55: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project QSanguosha (kit: Desktop Qt 5.4.2 clang 64bit)
When executing step "Make"
20:37:55: Elapsed time: 00:02.

网上搜了下似乎是要改-mmacosx-version-min？但是不知道去哪里改，请大佬指导

**Comment by Fsu0413** [comment]
Qt 5.4.2是2015年左右的产物，macOS 10.13应该在2017~2018年左右，应该是xcode版本匹配不上

**Comment by KiritoStudio** [comment]
@Fsu0413  xcode版本是xcode10，我想请教一下，/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ 以及之后的那些参数是在哪里生成的？源代码里翻了一下好像没找到

**Comment by Fsu0413** [comment]
都是qmake生成的

**Comment by KiritoStudio** [comment]
@Fsu0413 感谢，经过尝试发现更改10.7改成10.9就可以编译了。但是还有2个问题，一个是编译出来的是英文的界面，不知道怎么改。另外一个是原教程里的"ai-selector/","developers","rule"这几个文件夹似乎都找不到，请问是不用管吗？

**Comment by Fsu0413** [comment]
把整个文件夹的内容复制到和QSanguosha同级的目录应该就行吧，我有点忘了
