### ISSUE TITLE
提示信息

### ISSUE THREAD

**Issue by zhujingwei** [Mogara/QSanguosha-v2#20]
有点挡五谷之类的。。但字体又不够显眼。。

**Comment by Fsu0413** [comment]
然而我并不喜欢t神版的提示信息

**Comment by zhujingwei** [comment]
那就不用他的，来个更爽的也好

**Comment by sunnyadn** [comment]
啦啦说尽量不要给这个项目添加new feature :disappointed: ，方便人员注意力转移到Cardirector，不知代理组长怎么看。。。

**Comment by Fsu0413** [comment]
旧框架代理组长表示这个issue直接close更好
