### ISSUE TITLE
界限突破张辽（标准包）突袭会连续播放2次配音

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#26]
如题，听起来很奇怪。
之后检查代码，发现没有那句播放配音的语句，推测是突袭一共获得2牌，1牌1次。
赶脚这个地方应该改为拿牌之前播放。

**Comment by zhujingwei** [comment]
好主意

**Comment by Fsu0413** [comment]
原因明确，突袭本身是技能卡，没写mute= true，会播放配音，而发动突袭后，触发技里又有播放配音函数调用，还会播放配音，因此会播放两次
