### ISSUE TITLE
开局前一次性添加多个robot时出现音效重叠

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#27]
如题。
多次声音一齐播放，听起来就很奇怪了。。。
所以这个地方若改为每次只播放一次音效，不论添加多少robot，这样就好了
（该情况，在1217中，不存在

**Comment by zhujingwei** [comment]
我也不知道为什么，只要有配音，就一定会发动，不管其他的。。

**Comment by Fsu0413** [comment]
原因已明确，playaudioeffect的参数问题
