### ISSUE TITLE
旧张辽突袭后，点投降会出现问题

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#28]
如题。
发动 突袭后，点投降，游戏界面停止，手牌无法点击，但不会弹出游戏结束的框，

不发达突袭，直接摸牌，然后点投降，可以正常结束游戏

**Comment by Fsu0413** [comment]
投降现在有问题，原因暂不明确，出现问题后托管可以结束回合，不会影响接下来的流程

**Comment by zhujingwei** [comment]
AI大法好！

**Comment by sunnyadn** [comment]
我这里似乎没有重现，请提供更为详细的重现方法 @dragon100a

**Comment by Fsu0413** [comment]
@sunnylife 和旧张辽毫无关系，投降的问题不知道是什么鬼

**Comment by Fsu0413** [comment]
wontfix
