### ISSUE TITLE
ai非策略性问题汇总

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-v2#29]
- [x] 1、张辽突袭，无视手牌数
- [x] 2、周瑜犯贱，“无色”吓尿
- [x] 3、黄盖“超级一波大苦肉”
- [x] 4、甲鱼完杀变摆设
- [x] 5、刘协密诏，扔光手牌
- [x] 6、雇佣“慎行”，使用两张一样的牌
- [x] 7、鬼才只用手牌
- [x] 8、大乔回合内多次国色
- [x] 9、伏皇后求援可以给除了闪之外的牌
- [x] 10、蔡夫人献州一张装备4人受伤害
- [x] 11、蔡夫人/黄巾雷使拿着一把朱雀羽扇不停的发动献州
- [x] 12、献州不停发动（不确定）
- [x] 13、朱然胆守攻击范围外的人
- [x] 14、顾雍慎行弃置两张一样的牌
  ![image](https://cloud.githubusercontent.com/assets/7959436/7087960/d945fc88-dfc2-11e4-962d-b7ab338ec21b.png)
- [x] 15、程普濒死求两桃时，自己发动两次醇醪，阶段内其实只允许发动一次

**Comment by dragon100a** [comment]
非策略性问题汇总

实际上 说的是 ai无视规则，出现bug的行为吧

**Comment by Fsu0413** [comment]
对

**Comment by zyun7799** [comment]
献州不停发动是发生了卡死。。不知原因【fixed】

**Comment by dragon100a** [comment]
![3](https://cloud.githubusercontent.com/assets/5362072/7228698/66be683e-e78e-11e4-8b02-170d6aa9fe58.png)
拼点张角胜利后，杀了一刀袁术，然后出了3个没有目标的杀

**Comment by zyun7799** [comment]
程普不是ai问题，人也可以用

**Comment by zhujingwei** [comment]
蛊惑使用杀有时会不指定任何目标

**Comment by dragon100a** [comment]
@zhujingwei 
第一个，张辽的问题，好像是没解决？

**Comment by zhujingwei** [comment]
@dragon100a 
貌似我没遇到过
