### ISSUE TITLE
好像装备区的点数，真的被吃了

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#31]
武将只是用“一、二、三”这样的数字显示了距离。
防具坐骑和木马，有花色，没有点数

**Comment by Fsu0413** [comment]
全身没问题，非全身有问题
@bigambition

**Comment by bigambition** [comment]
我发现了，是字体的问题 用arial就没问题可以显示点数，用font/font.ttf就不行

**Comment by Fsu0413** [comment]
废话……
