### ISSUE TITLE
AI 白板问题汇总

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-v2#32]
- [x] 1、凌统
- [x] 2、陆逊
- [x] 3、程普（醇醪2）
- [x] 4、华佗（除疠）
- [x] 5、老张辽
- [x] 6、卧龙八阵
- [x] 7、赵云涯角（没AI？）
- [x] 8、缺利驭AI
- [x] 9、程昱不发动设伏和贲育 
- [x] 10、千幻缺AI
- [x] 11、旱魃只焚天不会心惔敌人
- [x] 12、朱灵无ai
- [x] 13、界sp马超不会发动追击

**Comment by Fsu0413** [comment]
暂不处理…………等非策略性的bug先处理完了再说

**Comment by dragon100a** [comment]
程昱  好像也有，没发动过貌似

**Comment by dragon100a** [comment]
![default](https://cloud.githubusercontent.com/assets/5362072/7002380/4093d8dc-dc7c-11e4-97fb-25a40eb0eced.png)
我感觉好像没看到界限徐庶 觉醒后，发动荐言。先打入禁表再说。
0.1保存录像的txt之后，我尝试用转换工具，转成png然后才能上传到这里。
0.5再将png转换回txt，得到的文件与转换前的一样，说明这个功能确实可用
1.文件播放到结尾的时候，弹出来警告框，写着：文件不可读，结束了。

**Comment by dragon100a** [comment]
![default](https://cloud.githubusercontent.com/assets/5362072/8276188/e1593b2c-18e5-11e5-9227-330592c3f2ad.png)
判定成功后，咆哮会使用，但是武圣不会用，不知道把红色牌当杀用，而是直接弃掉了闪。
