### ISSUE TITLE
AI策略问题汇总

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-v2#34]
- [x] 1、李儒无脑绝策
- [x] 2、曹真无脑司敌
- [x] 3、李儒开大电脑都不会选择弃牌
- [x] 4、AI无视沮授的失北，沮授对家只能出一张杀的输出也会打沮授，沮授被打也是有防御牌就出
- [x] 5、电脑发动倚天剑时目标是自己。。
  ![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=cb2716af30a85edffa8cfe2b795509d8/f53e8613632762d08015db40a4ec08fa503dc67c.jpg)
- [x] 6、队友质疑于吉蛊惑
- [ ] 7、主忠内3人忠臣4点制霸孙策3点被认为是内奸
- [x] 8、吉本亮出一张闪给主公张角 然后杀张角 被张角雷劈了
- [ ] 9、孙鲁育不知道为何总是魅步队友；

**Comment by zhujingwei** [comment]
BOSS模式反贼会救主公。。只要有桃，程普貌似只要有醇，就不会杀

**Comment by dragon100a** [comment]
大乔身上有兵和乐，先判定兵，中了，然后 判定乐的时候，手里就1个无懈。
此时就不该出无懈了。
http://tieba.baidu.com/p/3679040852
录像在链接里面，我终于知道为什么之前会有图片形式的录像文件了。。原来这里 不支持 文本录像上传

**Comment by zyun7799** [comment]
@dragon100a 已尝试调整

**Comment by dragon100a** [comment]
![default](https://cloud.githubusercontent.com/assets/5362072/7226350/ba756a5e-e77a-11e4-978b-3425719223fb.png)
短兵后，应该立即接相关的操作，要不然这个短兵没有意义。要么先放大象，然后短兵-杀，要么先短兵-杀，然后大象，录像里面是先短兵然后大象，再杀，如果丁奉是断杀的，那一开始的短兵就是没意义的。
@zyun7799 ，已经知道上述改动，新版已经完成编译，运行中。

**Comment by dragon100a** [comment]
![ai](https://cloud.githubusercontent.com/assets/5362072/7228853/f20227d6-e78f-11e4-93c1-13eaa804aec5.png)
对于潘璋马忠，ai应考虑优先拆除其武器，要不然之后每次2血 影响非常大。

**Comment by DGAH** [comment]
孙皓手中剩余一张【酒】和一张【杀】，原想酒杀目标，可惜“残蚀”已发动，使用【酒】之后只能把【杀】弃了……

-----【fixed-20150424】

**Comment by dragon100a** [comment]
![default](https://cloud.githubusercontent.com/assets/5362072/7448713/1a242c2c-f254-11e4-949c-61658ccba654.png)
曹彰1血手里是个无懈可击。且有距离，这个时候发动 将驰 少摸1牌 去打上家的刘协，不合逻辑。
完全可以不发动技能摸牌2张，再打刘协，或者 发动将驰 摸3张 不出杀。
@zyun7799

**Comment by Fsu0413** [comment]
剩下的wontfix
