### ISSUE TITLE
配图问题

### ISSUE THREAD

**Issue by zhujingwei** [Mogara/QSanguosha-v2#36]
我一直觉得夜叉和罗刹的配图反了，罗刹有胸，夜叉要丑。。

**Comment by Fsu0413** [comment]
没玩过OL打鬼不清楚……谁玩过OL打鬼给个图

**Comment by zhujingwei** [comment]
你看武将性别就知道了，尽管图是反的，但性别是对的，男的不可能有胸吧？

**Comment by sunnyadn** [comment]
有理有据令人信服 :joy:

**Comment by zyun7799** [comment]
经查，ol介绍页面上，夜叉为男，罗刹为女

**Comment by zyun7799** [comment]
同时发现，魅和魉也是女的。。。但是长得实在是太丑了，就保持男的不改了吧。。。

**Comment by zhujingwei** [comment]
23333
