### ISSUE TITLE
sp武将隐藏

### ISSUE THREAD

**Issue by zhujingwei** [Mogara/QSanguosha-v2#37]
SP甘夫人，SP潘凤，SP诸葛瑾......等武将不应该被隐藏，因为他们算是独立的武将，而且如果隐藏了，不开原来的武将所在的包的话，根本就选不到这些武将，你们说呢?

**Comment by Fsu0413** [comment]
这倒是……我回去看看

**Comment by dragon100a** [comment]
关于武将隐藏的问题，我曾经就在1217改进的那个帖子里面说过，如下武将建议取消隐藏，供参考
sp诸葛瑾（以下sp前缀省略）、潘凤、丁奉、何太后、

**Comment by Fsu0413** [comment]
诸葛瑾改不了，别的都可以

**Comment by dragon100a** [comment]
src/package/sp.cpp
General *sp_zhugejin = new General(this, "sp_zhugejin", "wu", 3, true, true);
诸葛瑾已经戴了true，看起来是没有隐藏的啊

**Comment by Fsu0413** [comment]
戴了true是隐藏

**Comment by dragon100a** [comment]
@Fsu0413 
诸葛瑾 为什么改不了呢？

**Comment by zyun7799** [comment]
那是不是还应该删掉“国战身份局”包中的同名武将，防止重复

**Comment by Fsu0413** [comment]
……不用删……隐藏掉就行了

**Comment by Fsu0413** [comment]
@dragon100a 诸葛瑾如果在3v3包里隐藏的话，3v3模式就选不到他了

**Comment by dragon100a** [comment]
@Fsu0413 
假设这样的情况：玩身份局，只开sp包，外加标准，风火林山，一将成名系列，怀旧系列
这个情况下，诸葛瑾 取消隐藏，会出问题吗？

**Comment by Fsu0413** [comment]
不玩3v3就没问题，不过发布版本不能不考虑3v3

**Comment by dragon100a** [comment]
@Fsu0413 
诸葛瑾，在3v3包不隐藏，sp包不隐藏。
玩3v3的时候只选3v3、3v3扩展，外加标准什么的，不选sp包
玩身份局的时候，不选3v3、3v3扩展的包，这样会出问题吗？

**Comment by Fsu0413** [comment]
你麻烦不麻烦……另外还有人愿意在身份局玩文聘呢，怎么办

**Comment by dragon100a** [comment]
@Fsu0413 
不麻烦，什么模式选什么包，是很正常的情况。——这个要明确
文聘 不是问题，sp里有文聘

**Comment by Fsu0413** [comment]
文聘为何不是问题……两个文聘技能都不一样替换个毛
乱选不是不靠谱，玩的就是DIY
