### ISSUE TITLE
贴吧反馈bug汇总

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-v2#39]
- [x] 法正收到木牛可以发动恩怨（这是个普遍问题，所有卡牌移动都要改）
- [x] 晋宣帝的描述修改为“强制发动的非锁定技”（正在与bug报告者商讨）
- [x] 神司马不能制衡（什么鬼）
- [ ] attachedlordskill时机加入Debut
- [x] 民间国战模式fix（可能wontfix，这模式真心不想维护了……反正有官国我是不玩）
- [ ] mac版“启动服务器”等按钮在dock下面
- [x] 陈群经常性无法定品基本牌,有时候出牌阶段开始时点定品基本牌全灰，大概一局会有一半的几率出现
- [x] .牛金只要人死就裂围（不管是不是他杀的）（wontfix解决）
- [x] 旧徐庶举荐三张牌没对象
- [x] 徐庶株害刘封弃逆后不产生效果
  ![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=73fcb5ebb8315c6043956be7bdb0cbe6/0bfe1ddfa9ec8a13f0254e1ef303918fa1ecc067.jpg)
- [ ] 遗计牌不收入手牌，以及由此导致的-1手牌问题。。。
  录像：http://pan.baidu.com/s/1o65fTb0
- [x] 铁索两角色，如果属性死一个，铁索不会继续结算，仍留在另一角色头上

**Comment by Fsu0413** [comment]
神司马不能制衡经查为0401-2的Bug

**Comment by zyun7799** [comment]
支持删掉民间国战。。

**Comment by zhujingwei** [comment]
+1

**Comment by Fsu0413** [comment]
@ainomelody 帮忙统计……最近好几天没去看bug贴了，等我把NightlyBuilder做完再来看这里

**Comment by ainomelody** [comment]
等周五吧。。

**Comment by Fsu0413** [comment]
徐庶诛害刘封那个已找到原因，是因为XiansiSlashCard的validate中判断了杀的目标不在攻击范围内，不合理，取消了目标，然后由于目标为0，该视为杀作废了

**Comment by Fsu0413** [comment]
雇佣AI问题，@ainomelody 转移AI贴

**Comment by Fsu0413** [comment]
牛金wontfix

**Comment by Fsu0413** [comment]
剩下的wontfix
