### ISSUE TITLE
诸葛恪的黩武，配音什么时候播放？

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#40]
游戏里面我貌似没听到播放。
几个牌砸出去好像都没有播放

**Comment by dragon100a** [comment]
这是 个 问题，我是问 播放的实机是 什么？
我看到了这样的判断， if (subcards.length() <= 1)  else
这个判断的是 什么 含有？
@zyun7799

**Comment by Fsu0413** [comment]
这是个bug，fixed
