### ISSUE TITLE
游戏大厅，等待其他玩家进来的那个页面，背景图没有变化

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#42]
如题。
游戏的首页，点配置按钮，我更改了背景图，点确定，关闭游戏重新开。
那么游戏首页的背景图确实变化了。
点启动服务器，点单机启动，这个时候的背景图还是 default.jpg ，没有跟着刚才 配置按钮里面设定的变化。
这就意味着 等待大厅的背景图 无法设定了。这不科学。

**Comment by Fsu0413** [comment]
那个在skin里改

**Comment by dragon100a** [comment]
~/skins/defaultSkin.image.json
"tableBg": "image/system/backdrop/default.jpg",

这简直太隐晦了。游戏界面也没有地方改。
