### ISSUE TITLE
界限甘宁奇袭没有牌的目标

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#45]
如题，此外，黩武
![default](https://cloud.githubusercontent.com/assets/5362072/7196691/32df43d0-e509-11e4-8ee3-aff9383d2683.png)
似乎没有发动，在结尾的时候

**Comment by zyun7799** [comment]
界甘宁的奇袭与普甘宁的奇袭一样，没变过，不应该有问题呀。。。

**Comment by dragon100a** [comment]
@zyun7799 有没有问题 看录像就知道了。。。
其实 我一直想 修改ai的策略 以实现更加符合实际的打法。
不知道 有没有可以参考的手册

**Comment by zyun7799** [comment]
@dragon100a 像这样的问题，从代码里找不出原因，暂时也没办法修。
“修改ai的策略 以实现更加符合实际的打法”，这个事情其实一直在做，新写的技能ai中也是包含策略的。但是问题在于，现有的ai中函数相当多、关联也相当复杂，只能是根据测试中发现的问题一点点找出来调整。相关代码都在lua/ai文件夹里，技能的ai文件名就是所在包的名称，卡牌的ai在stand_cards-ai里，共用的策略函数在smart-ai里，都是用lua写成的，相关程序接口则在swig/ai.i里。

**Comment by zyun7799** [comment]
参考手册确实没有，只能看上面说的这些文件

**Comment by dragon100a** [comment]
@zyun7799
既然 这个修不了，那我先把他扔禁表吧。
另外，主忠反内的选将策略，能不能找到地方改？比如 曹丕主，我希望 太史慈这样的武将出来当忠，而不是钟会、邓艾 这种

**Comment by zyun7799** [comment]
选将策略也有的，在etc文件夹里，目测也是许久没有更新了

**Comment by dragon100a** [comment]
@zyun7799 
选将策略 看起来一共3个文件：loyalist、rebel、renegade。
1.不知道为什么没有关于主公的文件。
2.忠反2个文件，看起来分2个部分：
上面的部分是减号（-）+武将名+数字
下面的部分是 武将名+武将名+数字
3.内奸文件，减号（-）+武将名+数字

我想知道，减号、武将名以及数字的含义和取值范围。我打算尝试修改这些。

**Comment by zyun7799** [comment]
@dragon100a 目测是这样的：
对于忠、反、内的选将，会根据主公的名称和各个武将的考虑参数来选择武将，
每行左侧一栏是当前主公的武将名，减号表示在任意主公时都有效，
每行中间一栏是需要附加后面的考虑参数的某个武将名，
每行最后一栏则是在该主公情况下，对该武将的考虑参数，
参数越大，选择该武将的优先程度越高，参数越小，优先程度越低，没有参数的武将则默认参数为0，参数相同则在最大的中随机。
要改参数的话，为了方便比较，不要超过（-3,3）的范围。
三“栏”之间用空格分开，空格数量不限，尽量整齐为好。
这个事情工作量会比较大，建议在贴吧征集。

**Comment by dragon100a** [comment]
@zyun7799 
其实工作量到不一定是问题。
主要是这个东西会涉及到 写这个文件的人的主观的 想法。每个人的想法不同，那这些就不一定科学。我改的，我觉得对，但是别人不一定认同吧。这3个文件删了会影响游戏吗？
如果不影响，删了之后，就全部平均的概率。同时在贴吧说明改动的方法，让别人自己做似乎更好

**Comment by zyun7799** [comment]
@dragon100a 我之所以建议“在贴吧征集”，就是为了尽量做到“科学”和“大部分人认同”，因为据我所知，研究相关技巧的玩家不在少数。既然作为游戏的维护者，我更愿意自己从技术上完成这件事情，而玩家们只需要从内容上提供意见。当然，作为开源程序，每个人的自由改动也不受干涉。
现在就请你明确一下，是否愿意参与到游戏的维护中来，通过意见征集的方式帮助我们完善这个程序？如果是，这个光荣的任务就交给你了（不知道你有没有加入开发群），如果否，那么我作为暂时的ai维护者，短期内肯定是会开始做这件事情的。

**Comment by zyun7799** [comment]
晚上我就去发贴征集选将策略，
这贴的两个问题暂时看不出原因。先close吧

**Comment by dragon100a** [comment]
@zyun7799 
这几天github打不开，联系方式以及在百度私信给你了。
能帮忙改ai真是极好的
