### ISSUE TITLE
铁索连环的声音接口有吗？

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#48]
1.重铸
2.连上几个人
3.属性伤害解锁

上述情况 能播放播放声音吗？
如果能播放 请告知音频文件的文件名。

**Comment by Fsu0413** [comment]
1 @recast
2 3 chain

**Comment by dragon100a** [comment]
@Fsu0413 
情况很复杂，
第一问重铸是 在 audio\card下 男女配音都有的
第二问，音频文件位于audio\card\common\chain.ogg，连上几个人确实会播放这个文件的声音
第三问，属性伤害之后，我好像没有听到解锁的声音，也就是貌似没有chain.ogg的声音

情况3 请核实一下

**Comment by Fsu0413** [comment]
你没听到

**Comment by dragon100a** [comment]
@Fsu0413 
你打开国战，连上三四个人，火杀一个，你应该可以听到第一个中了火杀，先播放一个受到伤害1点声音，然后是解锁的声音，再是第二个受到1点伤害的声音，到最后一个人受到1点伤害的声音，然后是解锁的声音，共2次解锁的声音。——这个声音的播放逻辑，是合情合理的。
但是v2版 尝试了几次这个过程，我听到受到伤害1点的音效，却没有听到解锁的音效。
所以 两边 这块的代码  是不是不一样？
@zyun7799 
帮忙尝试一下 上述过程，看看  处于连环状态的角色 受属性伤害解锁时候，到底有没有解锁的音效。
