### ISSUE TITLE
韩当 弓骑 后，就没有然后了；属性杀链子，没有听到解锁的音效

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#52]
![22222](https://cloud.githubusercontent.com/assets/5362072/7471790/b6dcc97a-f35d-11e4-8aa5-32d09befbc95.png)

1分8秒左右，韩当发动弓骑，没有出杀，直接弃牌过
3分20秒左右，主公杀链子上的 关羽，同时链子上还有诸葛亮，杀中的音效出来了，然而没有链子被杀中而解锁的声音。

**Comment by Fsu0413** [comment]
解铁索声音修复

**Comment by Fsu0413** [comment]
wontfix
