### ISSUE TITLE
失去技能效果持续：更改实现

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-v2#6]
涉及技能：双雄 刺槐

**Comment by Fsu0413** [comment]
Fs的思路：flag改mark，修改双雄加时机
修改Client::setMark()函数，处理失去技能

**Comment by xusine** [comment]
@Fsu0413 具体的要怎么做

**Comment by Fsu0413** [comment]
先干掉skillStateChanged函数，相关的东西都干掉
然后参考国战移植

**Comment by Fsu0413** [comment]
我来吧

**Comment by Fsu0413** [comment]
@Xusine1131
Lua接口不用加，只需要在技能效果持续期间，放置一个Mark，名为：ViewAsSkill_xxxEffect  （xxx替换为视为技或触发技的技能的objectName）。此时在失去技能时就不会失去技能按钮，直到此Mark的数量被设置为0。

具体实现：（比如某技能的技能名为xxx）
在失去技能时，先判断当前ClientPlayer是否有形如“ViewAsSkill_xxxEffect”（xxx替换为技能的objectName）的Mark，如果有，则在客户端本地（此处注意！！服务端没有！！）添加一个形如“ViewAsSkill_xxxLost”的Mark，并且不删除技能按钮。（实现在RoomScene::detachSkill()中）
当一个形为ViewAsSkill_xxxEffect的Mark的数量被设置为0时，如果ClientPlayer有形如“ViewAsSkill_xxxLost”的Mark，并且技能列表里也没有xxx技能，则对“ViewAsSkill_xxxLost”的Mark在客户端进行清除，并且删除技能按钮。（实现在Client::setMark()中）
此方法改编于国战双雄的耦合，话说国战双雄的耦合是实现在Client::notifyProperty()函数中的，如果想解耦的话，按照这个思路解耦就行了。

**Comment by Fsu0413** [comment]
@SwordElucidator AI对可以使用视为技有一句hasFlag(skill:objectName())的判断，改为getMark("ViewAsSkill_" .. skill:objectName() .. "Effect") > 0

这段语句来源于之前双雄的实现，不过因为双雄修改了实现所以hasFlag已经没有实际作用了。

**Comment by xusine** [comment]
@Fsu0413 国战还需要这样搞API么

**Comment by Fsu0413** [comment]
@Xusine1131 不用
