### ISSUE TITLE
曹丕主，陈群反，ai不杀曹植

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#63]
http://pan.baidu.com/s/1sjI97TN
上面是录像。这盘 打了很久没法结束，只好投降。因此这盘录像在转换为图像的时候，失败了。

我觉得问题可能 在陈群的“法恩”上。这局的陈群是个玩家，不是ai。翻面或者横置都会涉及到法恩是否发动，因此我估计是ai那边没有判断法恩 是 仅对队友 使用的。
在曹植没有防具的情况下，这里有很多情况 ai 扔杀，不杀 曹植。估计是ai担心曹植酒诗会引起 法恩。
望修正。

**Comment by dragon100a** [comment]
@zyun7799

**Comment by Fsu0413** [comment]
wontfix
