### ISSUE TITLE
界限华佗不知道拆不同势力的角色

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#64]
![0000000000](https://cloud.githubusercontent.com/assets/5362072/8029256/365debb2-0ded-11e5-9976-ab323506858d.png)
只是拆1个角色，
这个问题出现至少2次了
http://tieba.baidu.com/p/3805618462，这里也有
@zyun7799

**Comment by Fsu0413** [comment]
wontfix
