### ISSUE TITLE
ai考虑增加鲁肃好施后缔盟牌的数量的判断

### ISSUE THREAD

**Issue by dragon100a** [Mogara/QSanguosha-v2#65]
![default](https://cloud.githubusercontent.com/assets/5362072/8075112/740d2216-0f6e-11e5-8a04-5ec72e4a90e4.png)
鲁肃先好施给忠，使得忠的手牌多，然后和牌少的反 缔盟。
这种情况下，应该 根据数量，来判定鲁肃是反。

但是录像中 主公和另外一个忠 没有 判断出来，望修正。

**Comment by Fsu0413** [comment]
wontfix
