### ISSUE TITLE
主视角全身UI

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha-v2#7]
现在的大头UI确实不太好看。

**Comment by thiswangba** [comment]
感觉很奇怪，特别是打了全身补丁以后，其他人都是全身的，就自己还是大头...

**Comment by zhujingwei** [comment]
+1

**Comment by YanGuam** [comment]
本人退出Mogara所有项目的开发，组长职权由高城代行。有兴趣完成这个issue的自便

**Comment by zhujingwei** [comment]
这是为何？

**Comment by YanGuam** [comment]
competed via commit e99b737b65bc5cff906fedb9a8de86af5a1b93f4
