### ISSUE TITLE
袁术的“伪帝”是否要改一下

### ISSUE THREAD

**Issue by zhujingwei** [Mogara/QSanguosha-v2#72]
我觉得现在的“伪帝”技能并不好，从客观的角度来说，OL的伪帝要好一些，而且应该便于实现。

OL”伪帝“：直接在武将技能栏添加主公的主公技，可以像主公一样发动。

神杀"伪帝“：不在武将技能栏添加其他技能，而是将伪帝替换为主公技，如果主公有多个主公技还会askforchoice选择发动的技能；而且由于神杀锁定技的技能按钮只有一种动画--灰的，所以当主公为刘备时，技能栏并没有任何表示，伪帝还是灰的（大家都知道灰的就是不能发动的意思），这不是误导吗？而且我看了一下源码，技能实现非常复杂。

所以我觉得神杀的伪帝还是改一下的好！

**Comment by zhujingwei** [comment]
顺便我还要报一个BUG：主公为孙策+★刘备的时候，SP袁术只能获得孙策的制霸，不能获得刘备的誓仇，当主公为★刘备+孙策的时候，SP袁术只能获得刘备的誓仇，不能获得孙策的制霸，怀疑是getskilllist的问题

**Comment by Fsu0413** [comment]
伪帝没必要改，改了还影响很多东西比如hasLordSkill的判定之类的。

**Comment by Fsu0413** [comment]
Bug求主视角录像。

**Comment by zhujingwei** [comment]
录像怎么给？

**Comment by zhujingwei** [comment]
可是技能不好发动啊

**Comment by zhujingwei** [comment]
好吧，偶发性BUG，无法重现了。。。

**Comment by zhujingwei** [comment]
![default](https://cloud.githubusercontent.com/assets/8627524/8406316/ad2aa9dc-1e8d-11e5-84a7-b561224c503f.jpg)
你们觉得这样好吗？

**Comment by Fsu0413** [comment]
反正我感觉没什么问题，实在不行让美工做个可以点击的锁定技按钮上去

**Comment by zhujingwei** [comment]
也行

**Comment by zhujingwei** [comment]
三国杀史上第一个可以主动点的锁定技，简直开创了先河

**Comment by Fsu0413** [comment]
要不然你行的话，你改一改伪帝，看看行不行，我会告诉你什么地方有问题。
这个技能，如果要实现你的效果，唯一的出路是改界面。

**Comment by zhujingwei** [comment]
实际上lua的版本我已经弄出来了

**Comment by zhujingwei** [comment]
我肯定会试试的

**Comment by Fsu0413** [comment]
建议你考虑一个函数：isLordSkill，你要想象一下你改了伪帝之后，这个函数如何处理

**Comment by Fsu0413** [comment]
记住源码不是Lua，不能认为效果类似就放出来，那是不行的。

**Comment by zhujingwei** [comment]
我会的

**Comment by zhujingwei** [comment]
编译是不是一定要用5.4.0?

**Comment by zhujingwei** [comment]
![image](https://cloud.githubusercontent.com/assets/8627524/8422849/857480f8-1f13-11e5-8153-d9020a51f787.png)
这怎么解决

**Comment by zhujingwei** [comment]
跪求代码规范，顺便你本来说的就是isLordSkill，不是hasLordSkill，顺便，你们也没解决chhttps://cloud.githubusercontent.com/assets/8627524/8431400/cc3da462-1f6b-11e5-8521-257361722abd.pngangehero

**Comment by zhujingwei** [comment]
跪求代码规范，顺便你本来说的就是isLordSkill，不是hasLordSkill，顺便，你们也没解决changehero
https://cloud.githubusercontent.com/assets/8627524/8431400/cc3da462-1f6b-11e5-8521-257361722abd.png

**Comment by Fsu0413** [comment]
代码规范，参考Qt的文档。
我说的是isLordSkill是我的错，不过我上文也说了hasLordSkill。
难道就因为我的一个typo你就不把代码考虑全面么

**Comment by zhujingwei** [comment]
我参考的是源码，难道源码也是不规范的？

**Comment by Fsu0413** [comment]
你参考的什么地方的源码？不规范我会改

**Comment by zhujingwei** [comment]
就是这个项目的其他技能

**Comment by zhujingwei** [comment]
![image](https://cloud.githubusercontent.com/assets/8627524/8433891/135cdb74-1f7b-11e5-8e6b-921e0add11c8.png)
你要的hasLordSkill

**Comment by zhujingwei** [comment]
反正我的思路你都已经看见了，麻烦你帮我改改

**Comment by zhujingwei** [comment]
![image](https://cloud.githubusercontent.com/assets/8627524/8434010/864bf66a-1f7b-11e5-964d-c20dc7aaea25.png)

**Comment by Fsu0413** [comment]
@BeginnerSlob

**Comment by zhujingwei** [comment]
────────游戏开始────────
姜伯约 摸了 4 张牌 闪[￼J], 无中生有[￼8], 杀[￼J], 的卢[￼5]
SP袁术 摸了 4 张牌
─────────────────────
姜伯约 摸了 2 张牌 顺手牵羊[￼J], 酒[￼9]
姜伯约 使用了 无中生有[￼8]
姜伯约 摸了 2 张牌 杀[￼8], 乐不思蜀[￼6]
姜伯约 发动了“殉志”
姜伯约 摸了 3 张牌 雷杀[￼7], 杀[￼6], 赤兔[￼5]
姜伯约 变身为 刘备
SP袁术 获得了技能“激将”
刘备 变身为 曹操
SP袁术 失去了技能“激将”
SP袁术 获得了技能“护驾”

# 

我想我已经成功了！
