### ISSUE TITLE
三国杀在64位的系统无法使用扩展武将

### ISSUE THREAD

**Issue by johnnylau** [Mogara/QSanguosha-v2#79]
我设计了几个技能 都是在技能手册里的技能当作参考 原来在36位系统是可以用的 但我换成64位win7之后一用技能就崩溃...
请问你们测试的时候有没有这种bug的出现

**Comment by zhujingwei** [comment]
不会啊，我就是win8.1 x64的，可以用，你看看是不是方法改了

**Comment by johnnylau** [comment]
解决了 ....
重新编译了一遍 发现LoadTranslationTable最后多了个"," 删掉后好像就不会崩溃了
