### ISSUE TITLE
error C2065: 'QByteArrayList' : undeclared identifier

### ISSUE THREAD

**Issue by Alehap** [Mogara/QSanguosha-v2#83]
Hello,
Sorry I cannot know China as well, can you help me to fix this problem.
![23-07-2015 5-10-04 ch](https://cloud.githubusercontent.com/assets/7158050/8847975/0b190894-315e-11e5-816a-20d2158b238a.png)

Thanks too much :(
I've used Qt v 5.3.2 and swig 3.0.6

**Comment by xusine** [comment]
![bq2y o1o98 j 3jf og e](https://cloud.githubusercontent.com/assets/8319391/8848124/8a0b7c14-3167-11e5-9f2a-364abd5c5b52.png)
You'd better use Qt 5.4.2 instead.

**Comment by Alehap** [comment]
Oh thank you, I've been downloading the Qt version 5.5 ^^
I love SangGuoSha too much^^

**Comment by xusine** [comment]
@Alehap In my view, Qt 5.4.2 is the best choice. If you use Qt 5.5, it will be very slow when playing the awake effect.

**Comment by Alehap** [comment]
Oh thank you too much for suggesting me.
I'll download Qt 5.4.2

**Comment by Alehap** [comment]
BTW please help me for chosing suitable version. Is this right "qt-opensource-windows-x86-msvc2013-5.4.2.exe"

Thank you too much.

**Comment by Fsu0413** [comment]
In fact this program is not ready to support Qt5.5.
It is still using QtDeclarative which has been deceprated in 5.5.

I think it is not so hard to choose Qt version......
