### ISSUE TITLE
钟繇的活墨有问题

### ISSUE THREAD

**Issue by zhujingwei** [Mogara/QSanguosha-v2#89]
活墨: 每当你需要使用一张你于此回合内未使用过的基本牌时，你可以将一张黑色非基本牌置于牌堆顶，然后视为你使用了此基本牌。 
技能描述如上，“你于此回合内未使用过的基本牌”，不是“以此法”使用的基本牌

**Comment by Fsu0413** [comment]
确实有这个问题，想修也不难，你试试吧

**Comment by Fsu0413** [comment]
改法是这样的：
删掉HuomoCard::validate和HuomoCard::validateInResponse里面的setPlayerMark
给Huomo加个时机PreCardUsed，加个优先级为6，判断use.card是否为基本牌

tag["huomoClassName"] 也需要改

**Comment by Fsu0413** [comment]
wontfix
